version: "3"

services:

  my_nginx:
    platform: linux/x86_64
    image: nginx:latest
    container_name: my_nginx
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "127.0.0.1:80:80"
    networks:
      - my_network
  
  my_mysql:
    platform: linux/x86_64
    image: mysql:8.0.22
    container_name: my_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    cap_add:
      - SYS_NICE
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - my_network

  my_redis:
    platform: linux/x86_64
    image: redis:latest
    container_name: my_redis
    volumes:
      - ./data/redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - my_network

  my_postgres:
    platform: linux/x86_64
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - my_network

networks:
  my_network:
    external: true
